// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Avro;
using Avro.Specific;
namespace User
{
	
	public partial class UserCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Created\",\"namespace\":\"User\",\"fields\":[{\"name\":\"Email\",\"t" +
				"ype\":\"string\"},{\"name\":\"UserName\",\"type\":\"string\"},{\"name\":\"Role\",\"type\":\"string" +
				"\"}]}");
		private string _Email;
		private string _UserName;
		private string _Role;
		public virtual Schema Schema
		{
			get
			{
				return UserCreated._SCHEMA;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				this._UserName = value;
			}
		}
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				this._Role = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Email;
			case 1: return this.UserName;
			case 2: return this.Role;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Email = (System.String)fieldValue; break;
			case 1: this.UserName = (System.String)fieldValue; break;
			case 2: this.Role = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
